name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Build debug
      run: |
        ./gradlew pmdIntegrationTest --warning-mode all
        cat build/reports/pmd/integrationTest.html
        cat build/reports/problems/problems-report.html
    - name: Build
      run: ./gradlew check
    - name: Dependency check
      run: ./gradlew dependencyCheckAggregate
